[mypy]
exclude = ^(\.venv|\.vscode|\.local|__pycache__)/
python_version = 3.14
strict = False

[tool.mypy]
namespace-packages = True

[mypy-docxtpl.*]
ignore_missing_imports = True


[mypy-docx.*]
ignore_missing_imports = True

[mypy-python_docx_replace.*]
ignore_missing_imports = True


